name: Frontend CI

on:
  push:
    branches: [develop, master]
    paths:
      - 'too-doo-frontend/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'too-doo-frontend/**'
  workflow_dispatch:

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to runner
        uses: actions/checkout@v2

      - name: Set up JS environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        working-directory: too-doo-frontend
        run: yarn install

      - name: Run tests
        working-directory: too-doo-frontend
        run: yarn test